language: java

jdk: openjdk8

dist: trusty

cache:
    directories:
        - $HOME/.m2

script:
    - jdk_switcher use openjdk8
    - java -version
    - ./mvnw clean install
    - ./mvnw test

before_install:
    - chmod +x mvnw