language: java

jdk: 
  - openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  - jdk_switcher use openjdk8
  - java --version
  - ./mvnw clean install
  - ./mvnw test
  - ./mvnw failsafe:integration-test

before_install:
  - chmod +x mvnw